### ISSUE TITLE
Getting RuntimeError in resnet50 example

### ISSUE THREAD

**Issue by harpone** [JuliusKunze/jaxnet#22]
While running `examples/resnet50.py` (needed to change `loss.init_parameters(rng_key, *next(batches))` from `loss.init_parameters(*next(batches))` on line 100 apparently), I get

`RuntimeError: Internal: Unable to launch convolution with type forward and algorithm (0, none)`.

Completely mysterious to me, but maybe obvious to @JuliusKunze ?

**Comment by JuliusKunze** [comment]
Hey @harpone, thank you for pointing that out! I hadn't tested the resnet example after some API changes I made earlier today. Just [fixed it](https://github.com/JuliusKunze/jaxnet/commit/685230773070c64a1fed085f42f6b835cc75d6c1) and also updated the [colab version](https://colab.research.google.com/drive/1q6yoK_Zscv-57ZzPM4qNy3LgjeFzJ5xN#scrollTo=ScHwMb6qLxFI). Please let me know if you are running into more issues.
